name: CI/CD Pipeline TP

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupération du code
      - name: Recuperer le code du depot
        uses: actions/checkout@v4

      # Étape 2.1 : Connexion à Docker Hub (Utilise tes secrets)
      - name: Se connecter a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Étape 2.2 : Build et Push du Backend
      - name: Build et Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./springboot
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-backend:latest

      # Étape 2.3 : Build et Push du Frontend
      - name: Build et Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./angular-app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-frontend:latest
