name: CI/CD Pipeline TP

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le code du depot
        uses: actions/checkout@v4

      - name: Se connecter a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- ÉTAPE BACKEND (Chemin corrigé : springboot/app) ---
      - name: Build et Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./springboot/app
          file: ./springboot/app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-backend:latest

      # --- ÉTAPE FRONTEND (Chemin : angular-app) ---
      - name: Build et Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./angular-app
          file: ./angular-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-frontend:latest

      # --- ÉTAPE TEST (PARTIE 3) ---
      - name: Tester le lancement avec Docker Compose
        run: |
          docker compose up -d
          sleep 30
          docker compose ps
